# Generated by Django 4.0.3 on 2022-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Groups', 'verbose_name_plural': 'Group'},
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Group'),
        ),
    ]
